name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ env.Python3_ROOT_DIR }}/lib/python3.10/site-packages
          key: testing-packages-${{ hashFiles('**/setup.py') }}
      - name: Install dependencies
        run: pip install -e '.[linting]'
      - name: Lint Code
        run: python -m pylint --disable=line-too-long,too-many-lines,no-member ltm
      - name: Lint Tests
        run: pylint --disable=line-too-long,too-many-lines,no-member,missing-module-docstring,missing-class-docstring,missing-function-docstring test
        
  
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ env.Python3_ROOT_DIR }}/lib/python3.10/site-packages
          key: testing-packages-${{ hashFiles('**/setup.py') }}
      - name: Install dependencies
        run: pip install -e '.[testing]'
      - name: Run Tests
        run: python -m pytest
